# Generated by Django 5.0.4 on 2024-04-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerstionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
