# Generated by Django 5.0.4 on 2024-04-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerstionPedidos', '0002_alter_reserva_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
