# Generated by Django 5.0.4 on 2024-04-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerstionPedidos', '0003_delete_mesa_reserva_estado_alter_reserva_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estado',
            new_name='estado_reserva',
        ),
    ]
